# Application URL - Server
#url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

# Application URL - Local
url = http://localhost/orangeHRM/web/index.php/auth/login

#Browser Configuration
browser = chrome
#browser = firefox

#headless 
headless = true

#Credentials - Server
#username = admin
#password = admin123

#Credentials - Local
username = orangehrm_tarun
password = Tarun123@

#ImpicitWait (in sec)
implicitWait = 10

#Jenines system2ofc
#username = Tarunsai35
#password = Tarun123@
#java -jar "C:\Program Files\Jenkins\jenkins.war" --httpPort=9090